#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 25 05:39:19 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'areyousafe'
    mvnCommands = '--version'
    test='false'
}